### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by corysimmons** [Pachciar3/udemy-dark-mode-extension#21]
Sidebar turned white today
![image](https://github.com/Pachciar3/udemy-dark-mode-extension/assets/224636/3a78f8aa-41fb-46a1-b97b-bb55c29648ed)

**Comment by corysimmons** [comment]
For posterity, you can just add this to [Stylebot](https://chromewebstore.google.com/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha):

```css
html,
header[class^="header--header"],
[class*="app--header"],
[class^="app--sidebar-column"] *,
[class^="app--dashboard"] * {
  background: #111;
  color: #ccc;
  border-color: #222;
}

input[type="checkbox"] ~ svg use {
  color: transparent;
}

input[type="checkbox"][checked] ~ svg use {
  color: white;
}

[aria-current="true"] * {
  background: #222;
}

[aria-current="true"] input[type="checkbox"] ~ svg {
  border-color: #111;
}
```

![image](https://github.com/Pachciar3/udemy-dark-mode-extension/assets/224636/4544ac54-969c-47c1-b6dd-d7736220ce7c)
